-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE mailer_list (
    id integer DEFAULT nextval('mailer_id_seq'::regclass) PRIMARY KEY UNIQUE,
    email_id text NOT NULL,
    shoe_names text NOT NULL,
    gender text DEFAULT 'M'::text,
    frequency text DEFAULT 'O'::text,
    done text DEFAULT 'F'::text
);
COMMENT ON COLUMN mailer_list.id IS 'auto-incrementing PK';
COMMENT ON COLUMN mailer_list.email_id IS 'email-ID of the user';
COMMENT ON COLUMN mailer_list.shoe_names IS 'stores comma separated shoe-names - as received in the request';
COMMENT ON COLUMN mailer_list.gender IS 'M / F';
COMMENT ON COLUMN mailer_list.frequency IS '''O'' : One-Time  OR  ''D'' : Daily';
COMMENT ON COLUMN mailer_list.done IS 'T/F : indicates w/ this row has been processed or not';

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX mailer_pkey ON mailer_list(id int4_ops);
CREATE UNIQUE INDEX mailer_list_id_key ON mailer_list(id int4_ops);
