-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE shoe_price_hist (
    id SERIAL PRIMARY KEY,
    shoe_name text,
    website text,
    price_date text,
    price text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX shoe_price_hist_pkey ON shoe_price_hist(id int4_ops);
