-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE subscriber (
    id SERIAL PRIMARY KEY,
    subscriber_id text,
    shoe_names text,
    shoe_size text DEFAULT '8'::text,
    gender text DEFAULT 'M'::text,
    frequency text DEFAULT 'Once'::text,
    request_date text,
    subscription_status text DEFAULT 'Inactive'::text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX subscriber_pkey ON subscriber(id int4_ops);